# -*- coding: utf-8 -*-
"""Accounting NLP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14lH8qizoim8uMaJggPL0mcy-HX-yXA0H
"""

import pandas as pd
import numpy as np

def open_text(file_name):
  text_file = open(file_name, "r")
  data = text_file.read()
  text_file.close()
  return data

file_names = ["apple_2019.txt", "apple_2020.txt", "microsoft_2019.txt", "microsoft_2020.txt"]

texts = []
for i in file_names:
  texts.append(open_text(i))

from sklearn.metrics.pairwise import cosine_similarity

# Initialize an instance of tf-idf Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Generate the tf-idf vectors for the corpus
tfidf_matrix = tfidf_vectorizer.fit_transform(texts)

# compute and print the cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(cosine_sim)

for i in range(0, 4):
  print(file_names[i], [str(round(j, 2)) for j in cosine_sim[i]])

similarity = []
for i in range(0, 4):
  similarity.append([str(round(j, 2)) for j in cosine_sim[i]])

df_labels = []
for i in range(0, 4):
  df_labels.append(file_names[i].split(".txt")[0])

df = pd.DataFrame(similarity)
df.columns = df_labels
  
# Change the row indexes
df.index = df_labels
print(df.to_string())